backend/models/News.php
<?php

namespace app\models;

use Yii;
use yii\data\ActiveDataProvider;

/**
 * This is the model class for table "news".
 *
 * @property integer $news_id
 * @property string $date
 * @property integer $theme_id
 * @property string $text
 * @property string $title
 */
class News extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'news';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['date'], 'safe'],
            [['theme_id'], 'integer'],
            [['text'], 'string'],
            [['title'], 'string', 'max' => 255],
            [['text','title','date','themename'],'required'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'news_id' => '#ID',
            'date' => 'Дата',
            'theme_id' => 'Тема',
            'text' => 'Текст новости',
            'title' => 'Заголовок',
            'themename'=>'Тема',
        ];
    }
    /**
     * Метод для GridView, возвращает dataProvider
     * @param array $params Параметры из командной строки
     * @return ActiveDataProvider
     */
    
    public function search($params) {
        $query=self::find();
        $dataProvider=new ActiveDataProvider([
            'query'=>$query,
            'sort'=>array(
                'defaultOrder'=>['date'=>SORT_DESC],
            ),
            'pagination' => [
                'pagesize' => 5,
            ],
        ]);
        return $dataProvider;
    }
    
    /**
     * Опишем связь с таблицей themes
     */
    public function getThemes() {
        return $this->hasOne(Themes::className(), ['theme_id'=>'theme_id']);
    }
    
    /**
     * Геттер заголовков тем согласно связи
     * @return string Заголовок темы
     */
    public function getThemeName() {
        return $this->themes ? $this->themes->theme_title : "";
    }
    
    public function setThemeName($val) {
        $this->ThemeName=$val;
    }
    
}

frontend/models/News.php
<?php

namespace app\models;

use Yii;

use yii\db\Connection;
use yii\helpers\Url;
use yii\web\HttpException;
/**
 * Класс модели новостей
 * 
 */
class News extends \yii\base\Model
{
    /**
     * @var integer Количество новостей на одну страницу
     */
    public $itemsPerPage=5;
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'news';
    }
    /**
     * Имя таблицы тем
     * @return string
     */
    public static function tableThemeName() {
        return 'themes';
    }
    
    /**
     * Создадим массив Меню-календаря с пунктами в формате 
     * виджета yii\widgets\Menu;
     * по данным из БД
     * @return array Ассоциативный массив элементов меню
     */
    public static function makeYearMenuArray(){
        $connection=Yii::$app->getDb();
        /* Запрашиваем сгруппированный по месяцам список */
        $sql="SELECT YEAR(`date`) as year,MONTHNAME(`date`) as monthname,MONTH(`date`) as monthnum,COUNT(*) as cnt FROM ".self::tableName()." GROUP BY MONTH(`date`);";
        $cmd=$connection->createCommand($sql);
        $qr=$cmd->queryAll();
        /* Создаем массив требуемого формата */
        if (is_array($qr) && !empty($qr)) {
            $result=[];
            foreach ($qr as $r) {
        /* Чтобы все группировалось по годам, и избежать дополнительного запроса к БД, используем в качестве ключа год.
         * Создаем запись о годе если ее нет*/
                if (!array_key_exists($r["year"],$result)) {
                    $result[$r["year"]]=[
                        'label'=>$r["year"],
                        'url'=>Url::to(['/news/index','year'=>$r["year"]]),                   
                    ];
                }
        /* Докидываем в годы информацию о месяцах */
                $result[$r["year"]]['items'][]=[
                    'label'=>$r["monthname"]." (".$r["cnt"].")",
                    'url'=>Url::to(['/news/index','year'=>$r["year"],'monthnum'=>$r['monthnum']]),
                    'cnt'=>$r["cnt"],
                ];
            }
            
        }
     return $result;   
    }
   /**
    * Создадим массив меню тем,с пунктами в формате 
    * виджета yii\widgets\Menu;
    * по данным из БД
    * @return array Ассоциативный массив элементов меню
    */
    public static function makeThemesMenuArray(){
        $connection=Yii::$app->getDb();
        $sql="SELECT `news`.`theme_id`,`themes`.`theme_title`,COUNT(*) as cnt FROM `".self::tableName()."` JOIN `".self::tableThemeName()."` ON (`".self::tableName()."`.`theme_id`=`".self::tableThemeName()."`.`theme_id`) GROUP BY `news`.`theme_id`";
        $cmd=$connection->createCommand($sql);
        $qr=$cmd->queryAll();
        /* Создаем массив требуемого формата */
        if (is_array($qr) && !empty($qr)) {
            $result=[];
            foreach ($qr as $r) {
                $result[]=[
                    'label'=>$r["theme_title"]." (".$r["cnt"].")",
                    'url'=>Url::to(['/news/index','theme_id'=>$r['theme_id']]),
                ];
            }
        }
        return $result;
    }
    
/**
 * Получаем список новостей, согласно параметрам из Url
 * @return array Массив необходимых данных для шаблона
 * ['total_count'=>{total_count},'itemsperpage'=>{itemsPerPage},'items'=>{news_items}]
 */    
    public function newsList() {
        $params=  Yii::$app->request->get();
        /* Если страница не передана, берем нулевую */
        if (!isset($params['page']) || (int)$params['page']<1) $page=1; else $page=(int)$params['page'];
        /* Создадим sql - строку условий фильтрации */
        $where=""; 
        if (isset($params['theme_id'])) $where.=" AND `".$this->tableName ()."`.`theme_id`=:theme_id";
        if (isset($params['year'])) $where.=" AND YEAR(`date`)=:year";
        if (isset($params['monthnum']) && isset($params['year'])) $where.=" AND MONTH(`date`)=:monthnum";
        /* Создадим ограничения для пагинатора */
        $limit="";
        $start_line=($page-1)*$this->itemsPerPage;
        $limit=" LIMIT $start_line,$this->itemsPerPage";

        $connection=Yii::$app->getDb(); 
        /* Спросим у базы сколько вообще записей с такими условиями фильра в ней есть */
        $sql="SELECT COUNT(*) as cnt FROM `".$this->tableName()."` WHERE 1 ";
        $sql.=$where;
        $cmd=$this->prepareQuery($connection,$sql,$params);
        $qr=$cmd->queryOne();
        $total_count=(int)$qr["cnt"];
        /* Получим список всех записей подпадающих под фильтр */
        $sql="SELECT `news_id`,`date`,`news`.`title`,`text`,`themes`.`theme_title` as themename"
                . " FROM `".$this->tableName()."`"
                . " JOIN `".$this->tableThemeName()."`"
                . " ON (`".$this->tableName()."`.`theme_id`=`".$this->tableThemeName()."`.`theme_id`) "
                . "WHERE 1";       
        $sql.=$where;
        $sql.=$limit;       
        $cmd=$this->prepareQuery($connection,$sql,$params);
        $qr=$cmd->queryAll();
        if (!$qr) throw new HttpException(404,"Новости не найдены");
        /* Результирующий массив, содержащий в себе всю необходимую информацию */
        $result=['total_count'=>$total_count,'itemsperpage'=>$this->itemsPerPage,'items'=>$qr];
        return $result;
    }
    
    /**
     * Метод возвращает данные по одной новости
     * @param integer $news_id - идентификатор нужной новости
     * @return array массив данных новости
     * @throws HttpException вброс 404 если новость не найдена
     */
 
    public function Full($news_id) {
        $sql="SELECT `news_id`,`date`,`news`.`title`,`text`,`themes`.`theme_title` as themename"
                . " FROM `".$this->tableName()."`"
                . " JOIN `".$this->tableThemeName()."`"
                . " ON (`".$this->tableName()."`.`theme_id`=`".$this->tableThemeName()."`.`theme_id`) "
                . "WHERE news_id=:news_id";
        $connection=Yii::$app->getDb();
        $cmd=$connection->createCommand($sql,['news_id'=>(int)$news_id]);
        $qr=$cmd->queryOne();
        if (!$qr) throw new HttpException(404,"Такая новость не найдена");
        return $qr;
    }
    
    /* Биндим параметры к запросу */
    private function prepareQuery($connection,$sql,$params) {
        $cmd=$connection->createCommand($sql);
        if (isset($params['theme_id'])) $cmd->bindValue(":theme_id",(int)$params['theme_id']);
        if (isset($params['year'])) $cmd->bindValue(":year",$params['year']);
        if (isset($params['monthnum']) && isset($params['year'])) $cmd->bindValue(":monthnum",$params['monthnum']);       
        return $cmd;
    }
    
    
    
}

backend/controllers/NewsController.php
<?php

namespace backend\controllers;

use app\models\News;
use yii\helpers\Url;
use yii\web\HttpException;
/**
 * Класс - контроллер редактирования новостей
 * 
 */
class NewsController extends \yii\web\Controller
{
/**
 * Вывод списка новостей
 * @return html Страница со списком
 */
    public function actionIndex()
    {
        $model=new News();
        return $this->render('index',['model'=>$model]);
    }
    
    public function actionCreate() {
        $model=new News();
        $model->ThemeName='';
        $model->date=date("Y-m-d");
        return $this->renderAjax('newsform',['model'=>$model]);
    }
    
    public function actionUpdate($id=NULL) {
        $news_id=$id;
        if ($news_id) {
            $model=News::findOne($news_id);
            return $this->renderAjax('newsform',['model'=>$model]);
        } else throw new HttpException(404 ,'Item not found');
    }
    
    public function actionDelete($id=NULL) {
        $news_id=$id;
        if ($news_id) {
           $model=News::findOne($news_id);
           $model->delete();
           $this->redirect (Url::to('/news/index'));
        } else throw new HttpException(404 ,'Item not found');
    }
    
    public function actionSaveform($news_id=NULL){
        if (!$news_id) {
            $model=new News();
        } else {
            $model=News::findOne($news_id);
        }
        if ($model->load(\Yii::$app->request->post())) {
                if ($model->save()) {
                    $this->redirect (Url::to('/news/index'));
                } else \Yii::$app->getSession()->setFlash('error', 'Save error');
        } else {

        };  
    $this->redirect (Url::to('/news/index'));
    }

}

frontend/controllers/NewsController.php
<?php

namespace frontend\controllers;
use app\models\News;

class NewsController extends \yii\web\Controller
{
    public function actionIndex()
    {
        $model=new News();
        return $this->render('index',['model'=>$model]);
    }
    
    public function actionFull() {
        /* Здесь не будем передавать всю модель, а только массив данных для вывода. 
         * Ну чисто как другой способ, и шаблон будет "Чище" */
        $model=new News();
        $request=\Yii::$app->request->get();
        $news_id=$request['news_id'];
        $full=$model->Full($news_id);
        return $this->render('full',['full'=>$full]);       
    }
    
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

}

backend/views/news/index.php
<?php
/* @var $this yii\web\View */
use yii\grid\GridView;
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\Pjax;
use yii\bootstrap\Modal;
?>
<?php
/* Заставим модальное окно обновляться при каждом открытии */
$this->registerJs("$('body').on('hidden.bs.modal', '.modal', function () {
    $(this).removeData('bs.modal');
});");
?>
<h1>Редактирование новостей</h1>
<?php Pjax::begin(); ?>
<?php
    echo GridView::widget([
        'dataProvider'=>$model->search(Yii::$app->request->queryParams),
       /* 'filterModel'=>$model, */
        'tableOptions'=>['class'=>'ade_table table table-striped','id'=>$model->tableName()],
        'columns'=>[
            'news_id',
            'date:date',
            'ThemeName',
            'title',
            'text',
            ['class'=>'yii\grid\ActionColumn',
             'template'=>'{update} {delete}',
             'header'=>'Действия',
             'buttons'=>[
                 'update'=>function($url,$model) {
                    return Html::a('<span class="glyphicon glyphicon-pencil"></span>',$url,['class'=>'','data-toggle'=>'modal','data-target'=>'#editnews']);
                 }
             ],
            ]
        ],
    ]);

?>
        <?php echo Html::a('Добавить новость',['news/create'],['class'=>'btn btn-primary','data-toggle'=>'modal','data-target'=>'#editnews']);?>
<?php Pjax::end(); ?>

    <?php
       echo Modal::widget([
       'options'=>[
           'id'=>'editnews',
       ],
       'size'=>'modal-lg',
       'clientOptions'=>false,
    ]);

?>

backend/views/news/newsform.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use app\models\Themes;
use yii\jui\DatePicker;
?>
<div class="row">
    <div class="col-md-12">
        <div class="modal-form">
<?php $form = ActiveForm::begin([
    'id'=>'news-form',
    'action'=>Url::to(['/news/saveform','news_id'=>$model->news_id]),
    'options'=> [
        'class' => 'form-vertical',
        ],
]); ?>
<?php HTML::errorSummary($model); ?>
<div class="row">
    <div class="col-md-6">
       <?php echo $form->field($model,'date')->widget(DatePicker::className(),['name'=>'date',
           'value'=>date("Y-m-d"),
           'language'=>'ru-RU',
           'options'=>[
               'class'=>'form-control',
               'readonly'=>'readonly',
               ],
           'dateFormat'=>'yyyy-MM-dd',
           ]); ?>
    </div>
    <div class="col-md-6"><?php echo $form->field($model,'theme_id')->dropDownList(ArrayHelper::map(Themes::find()->All(), 'theme_id', 'theme_title'),['prompt'=>'Выберите тему']); ?></div>
</div>
    <?php echo $form->field($model,'title'); ?>
    <?php echo $form->field($model,'text')->textarea(['rows'=>6]); ?>
    <?php echo Html::submitButton('Сохранить', ['class' => 'btn btn-primary']); ?>
<?php 
     ActiveForm::end();
?>  
        </div>
    </div>
</div>